name: TestWorkflow

on:

  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      # ACTIONS_STEP_DEBUG: true
      MY_SECRET: ${{ secrets.DUMMY_SECRET }}
    steps:
      - name: Print secret
        id: first_step
        run: echo "Test=1234abc-$(date)" >> $GITHUB_OUTPUT
      - name: Print again
        run: echo ${{ steps.first_step.outputs.Test }}
      - name: And again
        run: echo ${{ join(steps.first_step.outputs.*, '\n') }}
