name: TestWorkflow

on:

  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      # ACTIONS_STEP_DEBUG: true
      MY_SECRET: ${{ secrets.DUMMY_MAIL }}
    steps:
      - name: Save secret
        run: echo "$MY_SECRET" | sed 's/./& /g' > mail.txt
      - name: Print secret
        run: cat mail.txt
      - name: Get output
        id: first_step
        run: echo "Test=$(cat mail.txt)" >> $GITHUB_OUTPUT
      - name: And again
        run: echo ${{ join(steps.first_step.outputs.*, '\n') }}
